help_url: https://wiki.piratenfraktion-nrw.de/wiki/HowTo:IT/AccountEditor
sections:
  - label: Deine Daten
    fields:
      - name: cn
        label: Name
        editable: false
        ldap_ignore: true
      - name: givenName
        label: Vorname
        editable: false
        ldap_ignore: true
        addressbook_ignore: true
      - name: sn
        label: Nachname
        editable: false
        ldap_ignore: true
        addressbook_ignore: true
      - name: displayName
        label: Angezeigter Name
        editable: true
        addressbook_ignore: true
      - name: nick
        label: Nickname
        editable: true
      - name: description
        label: Beschreibung
        editable: true
      - name: telephoneNumber
        label: Telefon
        editable: true
      - name: facsimileTelephoneNumber
        label: Fax
        editable: true
      - name: mobile
        label: Handy
        editable: true
      - name: roomNumber
        label: Raum
        editable: true
  - label: Deine Mail Adressen, f체r weniger oder mehr<br/>Adressen eine Mail an <a href="mailto:it@piratenfraktion-nrw.de">it@piratenfraktion-nrw.de</a> schreiben
    fields:
      - name: mail
        label: Mail
        editable: false
        ldap_ignore: true
  #- label: ""
  #  fields:
  #    - name: newPassword
  #      label: Neues Passwort
  #      editable: true
  #      ldap_ignore: true
  #      addressbook_ignore: true
  #      password: true
  #      hidden: false
  #    - name: newPasswordRepeat
  #      label: Neues Passwort Wdh.
  #      editable: true
  #      ldap_ignore: true
  #      addressbook_ignore: true
  #      password: true
  #      hidden: false
  - label: Dein Passwort kannst du 체ber den <a href="https://webmail.piratenfraktion-nrw.de">Zimbra Webmailer</a> 채ndern.<br/>Aktuelles Passwort zum 채ndern der Daten eingeben
    fields:
      - name: userPassword
        label: Passwort
        editable: true
        ignore_value: true
        ldap_ignore: true
        addressbook_ignore: true
        password: true
